name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - folium=0.9.1=py_0
  - geohash2=1.1=py_0
  - pip=19.1.1=py36_0
  - statsmodels=0.9.0=py36hfa6e2cd_1000
  - pip:
    - numpy==1.16.2
    - pandas==0.24.1
    - tensorflow==2.0.0b0

